commands:
  0: [BLUE, PURPLE, RED]
  1: [BLUE, RED, GREEN]
  2: [BLUE, GREEN, PURPLE]
  3: [RED, GREEN, BLUE]
  4: [PURPLE, BLUE, GREEN]
  5: [RED, BLUE, PURPLE]
  6: [GREEN, PURPLE, BLUE]
  7: [GREEN, RED, PURPLE]
  8: [RED, PURPLE, GREEN]
decode_reversed: false
